#!/usr/bin/env bash
# Configure nginx with custom HTTP header X-Served-By

apt-get update -y
apt-get install -y nginx

HOSTNAME=$(hostname)

echo "Holberton School" > /var/www/html/index.html

sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

systemctl restart nginx
