#!/usr/bin/env bash
# Install and configure HAProxy load balancer

apt-get update -y
apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy

cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local0
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 100.24.45.229:80 check
    server web-02 WEB02_IP:80 check
EOF

service haproxy restart
